# Generated by Django 3.1 on 2022-03-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="card_id",
            new_name="cart_id",
        ),
    ]
